# CloudFlare Worker Configuration for PartyMotivator
name = "partymotivator-locale-redirect"
main = "locale-redirect.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Worker Settings
[env.production]
account_id = "adac73aad31707d460592ff048806965" # Your CloudFlare Account ID
zone_id = "073c1a63fb415a89caf8095b043cf2ae"    # Your Domain Zone ID  

# Routes - runs on root path only
routes = [
    { pattern = "party-motivator.com/", zone_name = "party-motivator.com" },
    { pattern = "www.party-motivator.com/", zone_name = "party-motivator.com" }
]

# Variables for production
[env.production.vars]
ENVIRONMENT = "production"
DEBUG_LOGS = "false"

# Development settings
[env.development]
compatibility_date = "2024-01-15"

# Variables for development  
[env.development.vars]
ENVIRONMENT = "development"
DEBUG_LOGS = "true"

# KV Storage (for analytics - optional)
# [[kv_namespaces]]
# binding = "LOCALE_ANALYTICS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
